version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
    timezone: Etc/UCT
  ignore:
  - dependency-name: "@sapui5/ts-types"
    versions:
    - 1.86.3
    - 1.87.0
    - 1.87.1
    - 1.87.2
    - 1.87.3
    - 1.88.0
    - 1.88.1
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: husky
    versions:
    - 5.0.9
    - 5.1.0
    - 5.1.1
    - 5.1.2
    - 5.1.3
    - 5.2.0
  - dependency-name: typescript
    versions:
    - 4.1.4
    - 4.1.5
    - 4.2.2
    - 4.2.3
  - dependency-name: chai
    versions:
    - 4.3.0
    - 4.3.1
    - 4.3.3
