name: Continuous Integration
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  # See: https://github.community/t/duplicate-checks-on-push-and-pull-request-simultaneous-event/18012
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Full Build (node ${{ matrix.node_version }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version:
          - 16.x
          - 18.x
          - 20.x
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}

      - name: Install dependencies
        run: yarn

      - name: Build
        run: yarn run ci
